# Set base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source to working directory
COPY . .

# use uvicorn to run API in local
CMD ["uvicorn", "src.api_inference:app", "--host", "0.0.0.0", "--port", "8000"]