# Set base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source to working directory
COPY . .

# Run main (CMD is alternative)
ENTRYPOINT ["python", "src/main.py"]

# Get general.yaml if user not provide config_file param
CMD ["config.yaml"]